# Parametric Bottle Holder ğŸ¹ğŸ’§
**3D-printable, parametric mount for hamster water bottles.**  
Designed in OpenSCAD. Units: millimetres.

---

## ğŸ“ Overview
A hamster water bottle holder â€” acrylic-style replica.  

- **Dimensions (real-world):** 56 W Ã— 56 H Ã— 58 D; 50 mm inner span  
- **Parts:**  
  - Backplate (with 4 magnet pockets & rails)  
  - Cradle (with grooves)  
- Bottom floor included; narrow U-slot opens fully through the front rim.  

---

## âš™ï¸ Parameters

### Dimensions
- `back_w = 56` â€” backplate width  
- `holder_h = 56` â€” overall height  
- `depth_tot = 58` â€” wall to front-most edge  
- `inner_w = 50` â€” inside span (5 cm)  

### Thicknesses
- `wall_t = 3` â€” wall thickness  
- `bottom_t = 3` â€” bottom floor thickness  

### Magnet pockets (backplate)
- `mag_d = 12` â€” magnet diameter  
- `mag_t = 2.5` â€” pocket depth  
- `mag_mx = 10` â€” side margin  
- `mag_mz = 10` â€” top/bottom margin  

### Slide join (rails/grooves)
- `rail_w = 6` â€” rail width  
- `rail_t = 2.8` â€” rail protrusion  
- `rail_inset = 7` â€” inset from each side edge to centreline  
- `fit_clear = 0.30` â€” clearance per side inside grooves  

### Bottom U-slot (for spout)
- `slot_w = 14` â€” opening width (tweak if nozzle is wider)  
- `slot_depth = 24` â€” depth of slot from front  

---

## ğŸ›  Usage

Open the `.scad` file in OpenSCAD and tweak the parameters at the top to fit your specific water bottle.  

### Render / Export
```bash
# Preview in OpenSCAD GUI
openscad holder.scad

# Export STL (both parts together)
openscad -o exports/holder.stl holder.scad
